version: '3.9'
services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'carrental'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'Admin@123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Root@123'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
